---
title: 'Final Project: QuickDraw!'
author: "Lacey Etzkorn"
date: "11/16/2018"
output: 
	html_document:
		toc: true
---

## Motivation and Overview: 

**Provide an overview of the project goals and the motivation for it. Consider that this will be read by people who did not see your project proposal.**

Google's internet game QuickDraw prompts players to draw a given object. 
Such objects include an apple, a kangaroo, or the Eiffel Tower. 
You can play the game here: https://quickdraw.withgoogle.com. 
As the player draws the object, Google attempts to guess what the user is drawing. 
In fact, Google uses user-supplied doodles to train an object recognition algorithm.
Google has released some of the doodle data, and has opened up a Kaggle competition for teams to submit their own algorithms.

The goal of competing teams is to produce an algorithm that classifies doodles in a test set with the lowest mean average precision. Kaggle defines the mean average precision as follows:

$$\text{MAP}@3 = \sum_{u=1}^U \sum_{k=1}^{\min(n,3)} P(k)$$
where "$U$ is the number of scored drawings in the test data, $P(k)$ is the precision at cutoff $k$, and $n$ is the number predictions per drawing."

## Related Work: 

**Anything that inspired you, such as a paper, a web site, or something we discussed in class.**



## Initial Questions: 

**What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?**



## Data: 

**What is the data source? Document the data import, wrangling, etc.**

